# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               "eltonlaw"
subtitle:            "sundries"
tagline:             "Personal blog. Programming and etc."
url:                 "eltonlaw.github.io"
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              "Elton Law"
  github:            "eltonlaw"
  twitter:           "d0nkrs"
  twitch:            "d0nkrs"
  email:             "eltonlaw296@gmail.com"
defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: /post/:title
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
exclude: [vendor]
timezone: Canada/Eastern
